### ISSUE TITLE
컴시간 사이트 업데이트로 인한 오류

### ISSUE THREAD

**Issue by meronemo** [Coder-Iro/comcigan-py#16]
곧 개학이라서 라이브러리가 잘 작동하나 확인해보고 있었는데, 최근에 컴시간에서 또 사이트를 업데이트했는지 오류가 납니다.

```
from comcigan import School
school = School("수내중학교")
```

이 코드를 실행하면 아래와 같은 오류가 발생합니다.

```
Traceback (most recent call last):
  File "c:\Users\user\Desktop\test\test.py", line 2, in <module>
    school = School("수내중학교")
  File "c:\Users\user\Desktop\test\venv\lib\site-packages\comcigan\school.py", line 80, in __init__
    self.refresh()
  File "c:\Users\user\Desktop\test\venv\lib\site-packages\comcigan\school.py", line 93, in refresh
    self._week_data = [
  File "c:\Users\user\Desktop\test\venv\lib\site-packages\comcigan\school.py", line 94, in <listcomp>
    [
  File "c:\Users\user\Desktop\test\venv\lib\site-packages\comcigan\school.py", line 95, in <listcomp>
    [
  File "c:\Users\user\Desktop\test\venv\lib\site-packages\comcigan\school.py", line 96, in <listcomp>
    [
  File "c:\Users\user\Desktop\test\venv\lib\site-packages\comcigan\school.py", line 98, in <listcomp>
    subjects[int(str(x)[-2:])],
IndexError: list index out of range
```

**Comment by meronemo** [comment]
#11 작년에도 비슷한 이슈가 있었군요. 그쪽에 댓글을 남길걸 괜히 새 이슈를 열었네요, 죄송합니다.

**Comment by Coder-Iro** [comment]
새로 발생한 이슈는 새로 여는게 맞죠. 작년부터 뭔가 새 학기 되려고하면 구조변경하는거같네요... 일단 분석을 좀 해보겠습니다

**Comment by meronemo** [comment]
저도 어떻게 변경된건지 잠시 살펴보았는데요, 구조변경하면서 IP가 다시 112.186.146.81 로 바뀐 것 같습니다.
또 지금까지는 index를 뒤 두 글자에 숨겨놓아서 `subjects[int(str(x)[-2:])]` 이런식으로 시간표 데이터를 가져왔는데 이번엔 앞 두글자에 심어놓는 걸로 변경된 듯합니다.

**Comment by kms0219kms** [comment]
확인이 늦어 죄송합니다. 이 문재 제가 눈여겨 보고 있는데, 조만간 수정하겠습니다.

**Comment by kms0219kms** [comment]
IP 변경 -> 222.106.100.23
